export type TParticipantes = {
  Perfil: {
    Id: number
    Descricao: string
  }
  Categoria: {
    Id: number
    Descricao: string
  }
  ParticipanteId: number
  NomedaMae: string
  Status: string
  StatusUsuario: string
  Motivo: string
  PossuiSenha: true
  ReconhecimentoFacial: string
  CPF: string
  DataNascimento: string
  Nome: string
  SobreNome: string
  Email: string
  DDDCel: string
  Celular: string
  DDDTel: string
  Telefone: string
  CEP: string
  Estado: string
  Cidade: string
  Endereco: string
  Numero: string
  Complemento: string
  Bairro: string
  EstadoPostoFavorito: string
  CidadePostoFavorito: string
  BairroPostoFavorito: string
  PostoFavoritoID: number
  AceitouRegulamento: true
  RegulamentoUuid: string
  AceiteTermo: true
  TermoUuid: string
  Sexo: null
  SaldoMoeda: number
  KmExpirando: string
  DataDeExpiracao: string
  CompletouCadastro: true
  PerguntaSecretaID: null
  PerguntaSecreta: null
  RespostaSecreta: null
  TimeDoCoracaoID: null
  NomeTimeCoracao: null
  PossuiCartaoIpiranga: string
  PossuiAcumuloVeiculo: string
  Apelido: string
  SouAutonomo: string
  SaldoCombs: number
  Alerta: string
  DataCadastro: string
  DataAtualizacao: string
  OrigemCadastro: string
}
